# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_carray')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_carray')
    _carray = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_carray', [dirname(__file__)])
        except ImportError:
            import _carray
            return _carray
        try:
            _mod = imp.load_module('_carray', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _carray = swig_import_helper()
    del swig_import_helper
else:
    import _carray
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _carray.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _carray.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _carray.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _carray.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _carray.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _carray.SwigPyIterator_equal(self, x)

    def copy(self):
        return _carray.SwigPyIterator_copy(self)

    def next(self):
        return _carray.SwigPyIterator_next(self)

    def __next__(self):
        return _carray.SwigPyIterator___next__(self)

    def previous(self):
        return _carray.SwigPyIterator_previous(self)

    def advance(self, n):
        return _carray.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _carray.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _carray.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _carray.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _carray.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _carray.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _carray.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _carray.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class ios_base(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ios_base, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ios_base, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    erase_event = _carray.ios_base_erase_event
    imbue_event = _carray.ios_base_imbue_event
    copyfmt_event = _carray.ios_base_copyfmt_event

    def register_callback(self, __fn, __index):
        return _carray.ios_base_register_callback(self, __fn, __index)

    def flags(self, *args):
        return _carray.ios_base_flags(self, *args)

    def setf(self, *args):
        return _carray.ios_base_setf(self, *args)

    def unsetf(self, __mask):
        return _carray.ios_base_unsetf(self, __mask)

    def precision(self, *args):
        return _carray.ios_base_precision(self, *args)

    def width(self, *args):
        return _carray.ios_base_width(self, *args)
    if _newclass:
        sync_with_stdio = staticmethod(_carray.ios_base_sync_with_stdio)
    else:
        sync_with_stdio = _carray.ios_base_sync_with_stdio

    def imbue(self, __loc):
        return _carray.ios_base_imbue(self, __loc)

    def getloc(self):
        return _carray.ios_base_getloc(self)
    if _newclass:
        xalloc = staticmethod(_carray.ios_base_xalloc)
    else:
        xalloc = _carray.ios_base_xalloc

    def iword(self, __ix):
        return _carray.ios_base_iword(self, __ix)

    def pword(self, __ix):
        return _carray.ios_base_pword(self, __ix)
    __swig_destroy__ = _carray.delete_ios_base
    __del__ = lambda self: None
ios_base_swigregister = _carray.ios_base_swigregister
ios_base_swigregister(ios_base)
cvar = _carray.cvar
ios_base.boolalpha = _carray.cvar.ios_base_boolalpha
ios_base.dec = _carray.cvar.ios_base_dec
ios_base.fixed = _carray.cvar.ios_base_fixed
ios_base.hex = _carray.cvar.ios_base_hex
ios_base.internal = _carray.cvar.ios_base_internal
ios_base.left = _carray.cvar.ios_base_left
ios_base.oct = _carray.cvar.ios_base_oct
ios_base.right = _carray.cvar.ios_base_right
ios_base.scientific = _carray.cvar.ios_base_scientific
ios_base.showbase = _carray.cvar.ios_base_showbase
ios_base.showpoint = _carray.cvar.ios_base_showpoint
ios_base.showpos = _carray.cvar.ios_base_showpos
ios_base.skipws = _carray.cvar.ios_base_skipws
ios_base.unitbuf = _carray.cvar.ios_base_unitbuf
ios_base.uppercase = _carray.cvar.ios_base_uppercase
ios_base.adjustfield = _carray.cvar.ios_base_adjustfield
ios_base.basefield = _carray.cvar.ios_base_basefield
ios_base.floatfield = _carray.cvar.ios_base_floatfield
ios_base.badbit = _carray.cvar.ios_base_badbit
ios_base.eofbit = _carray.cvar.ios_base_eofbit
ios_base.failbit = _carray.cvar.ios_base_failbit
ios_base.goodbit = _carray.cvar.ios_base_goodbit
ios_base.app = _carray.cvar.ios_base_app
ios_base.ate = _carray.cvar.ios_base_ate
ios_base.binary = _carray.cvar.ios_base_binary
ios_base.ios_base_in = _carray.cvar.ios_base_ios_base_in
ios_base.out = _carray.cvar.ios_base_out
ios_base.trunc = _carray.cvar.ios_base_trunc
ios_base.beg = _carray.cvar.ios_base_beg
ios_base.cur = _carray.cvar.ios_base_cur
ios_base.end = _carray.cvar.ios_base_end

def ios_base_sync_with_stdio(__sync=True):
    return _carray.ios_base_sync_with_stdio(__sync)
ios_base_sync_with_stdio = _carray.ios_base_sync_with_stdio

def ios_base_xalloc():
    return _carray.ios_base_xalloc()
ios_base_xalloc = _carray.ios_base_xalloc

class ios(ios_base):
    __swig_setmethods__ = {}
    for _s in [ios_base]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ios, name, value)
    __swig_getmethods__ = {}
    for _s in [ios_base]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ios, name)
    __repr__ = _swig_repr

    def rdstate(self):
        return _carray.ios_rdstate(self)

    def clear(self, *args):
        return _carray.ios_clear(self, *args)

    def setstate(self, __state):
        return _carray.ios_setstate(self, __state)

    def good(self):
        return _carray.ios_good(self)

    def eof(self):
        return _carray.ios_eof(self)

    def fail(self):
        return _carray.ios_fail(self)

    def bad(self):
        return _carray.ios_bad(self)

    def exceptions(self, *args):
        return _carray.ios_exceptions(self, *args)

    def __init__(self, __sb):
        this = _carray.new_ios(__sb)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _carray.delete_ios
    __del__ = lambda self: None

    def tie(self, *args):
        return _carray.ios_tie(self, *args)

    def rdbuf(self, *args):
        return _carray.ios_rdbuf(self, *args)

    def copyfmt(self, __rhs):
        return _carray.ios_copyfmt(self, __rhs)

    def fill(self, *args):
        return _carray.ios_fill(self, *args)

    def imbue(self, __loc):
        return _carray.ios_imbue(self, __loc)

    def narrow(self, __c, __dfault):
        return _carray.ios_narrow(self, __c, __dfault)

    def widen(self, __c):
        return _carray.ios_widen(self, __c)
ios_swigregister = _carray.ios_swigregister
ios_swigregister(ios)

class ostream(ios):
    __swig_setmethods__ = {}
    for _s in [ios]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, ostream, name, value)
    __swig_getmethods__ = {}
    for _s in [ios]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, ostream, name)
    __repr__ = _swig_repr

    def __init__(self, __sb):
        this = _carray.new_ostream(__sb)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _carray.delete_ostream
    __del__ = lambda self: None

    def __lshift__(self, *args):
        return _carray.ostream___lshift__(self, *args)

    def put(self, __c):
        return _carray.ostream_put(self, __c)

    def write(self, __s, __n):
        return _carray.ostream_write(self, __s, __n)

    def flush(self):
        return _carray.ostream_flush(self)

    def tellp(self):
        return _carray.ostream_tellp(self)

    def seekp(self, *args):
        return _carray.ostream_seekp(self, *args)
ostream_swigregister = _carray.ostream_swigregister
ostream_swigregister(ostream)
cin = cvar.cin
cout = cvar.cout
cerr = cvar.cerr
clog = cvar.clog

class istream(ios):
    __swig_setmethods__ = {}
    for _s in [ios]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, istream, name, value)
    __swig_getmethods__ = {}
    for _s in [ios]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, istream, name)
    __repr__ = _swig_repr

    def __init__(self, __sb):
        this = _carray.new_istream(__sb)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _carray.delete_istream
    __del__ = lambda self: None

    def __rshift__(self, *args):
        return _carray.istream___rshift__(self, *args)

    def gcount(self):
        return _carray.istream_gcount(self)

    def get(self, *args):
        return _carray.istream_get(self, *args)

    def getline(self, *args):
        return _carray.istream_getline(self, *args)

    def ignore(self, *args):
        return _carray.istream_ignore(self, *args)

    def peek(self):
        return _carray.istream_peek(self)

    def read(self, __s, __n):
        return _carray.istream_read(self, __s, __n)

    def readsome(self, __s, __n):
        return _carray.istream_readsome(self, __s, __n)

    def putback(self, __c):
        return _carray.istream_putback(self, __c)

    def unget(self):
        return _carray.istream_unget(self)

    def sync(self):
        return _carray.istream_sync(self)

    def tellg(self):
        return _carray.istream_tellg(self)

    def seekg(self, *args):
        return _carray.istream_seekg(self, *args)
istream_swigregister = _carray.istream_swigregister
istream_swigregister(istream)

class iostream(istream, ostream):
    __swig_setmethods__ = {}
    for _s in [istream, ostream]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, iostream, name, value)
    __swig_getmethods__ = {}
    for _s in [istream, ostream]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, iostream, name)
    __repr__ = _swig_repr

    def __init__(self, __sb):
        this = _carray.new_iostream(__sb)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _carray.delete_iostream
    __del__ = lambda self: None
iostream_swigregister = _carray.iostream_swigregister
iostream_swigregister(iostream)

endl_cb_ptr = _carray.endl_cb_ptr

def endl(arg1):
    return _carray.endl(arg1)
endl = _carray.endl
ends_cb_ptr = _carray.ends_cb_ptr

def ends(arg1):
    return _carray.ends(arg1)
ends = _carray.ends
flush_cb_ptr = _carray.flush_cb_ptr

def flush(arg1):
    return _carray.flush(arg1)
flush = _carray.flush
class vectori(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectori, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectori, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _carray.vectori_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _carray.vectori___nonzero__(self)

    def __bool__(self):
        return _carray.vectori___bool__(self)

    def __len__(self):
        return _carray.vectori___len__(self)

    def __getslice__(self, i, j):
        return _carray.vectori___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _carray.vectori___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _carray.vectori___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _carray.vectori___delitem__(self, *args)

    def __getitem__(self, *args):
        return _carray.vectori___getitem__(self, *args)

    def __setitem__(self, *args):
        return _carray.vectori___setitem__(self, *args)

    def pop(self):
        return _carray.vectori_pop(self)

    def append(self, x):
        return _carray.vectori_append(self, x)

    def empty(self):
        return _carray.vectori_empty(self)

    def size(self):
        return _carray.vectori_size(self)

    def swap(self, v):
        return _carray.vectori_swap(self, v)

    def begin(self):
        return _carray.vectori_begin(self)

    def end(self):
        return _carray.vectori_end(self)

    def rbegin(self):
        return _carray.vectori_rbegin(self)

    def rend(self):
        return _carray.vectori_rend(self)

    def clear(self):
        return _carray.vectori_clear(self)

    def get_allocator(self):
        return _carray.vectori_get_allocator(self)

    def pop_back(self):
        return _carray.vectori_pop_back(self)

    def erase(self, *args):
        return _carray.vectori_erase(self, *args)

    def __init__(self, *args):
        this = _carray.new_vectori(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _carray.vectori_push_back(self, x)

    def front(self):
        return _carray.vectori_front(self)

    def back(self):
        return _carray.vectori_back(self)

    def assign(self, n, x):
        return _carray.vectori_assign(self, n, x)

    def resize(self, *args):
        return _carray.vectori_resize(self, *args)

    def insert(self, *args):
        return _carray.vectori_insert(self, *args)

    def reserve(self, n):
        return _carray.vectori_reserve(self, n)

    def capacity(self):
        return _carray.vectori_capacity(self)
    __swig_destroy__ = _carray.delete_vectori
    __del__ = lambda self: None
vectori_swigregister = _carray.vectori_swigregister
vectori_swigregister(vectori)

class vectord(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectord, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectord, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _carray.vectord_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _carray.vectord___nonzero__(self)

    def __bool__(self):
        return _carray.vectord___bool__(self)

    def __len__(self):
        return _carray.vectord___len__(self)

    def __getslice__(self, i, j):
        return _carray.vectord___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _carray.vectord___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _carray.vectord___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _carray.vectord___delitem__(self, *args)

    def __getitem__(self, *args):
        return _carray.vectord___getitem__(self, *args)

    def __setitem__(self, *args):
        return _carray.vectord___setitem__(self, *args)

    def pop(self):
        return _carray.vectord_pop(self)

    def append(self, x):
        return _carray.vectord_append(self, x)

    def empty(self):
        return _carray.vectord_empty(self)

    def size(self):
        return _carray.vectord_size(self)

    def swap(self, v):
        return _carray.vectord_swap(self, v)

    def begin(self):
        return _carray.vectord_begin(self)

    def end(self):
        return _carray.vectord_end(self)

    def rbegin(self):
        return _carray.vectord_rbegin(self)

    def rend(self):
        return _carray.vectord_rend(self)

    def clear(self):
        return _carray.vectord_clear(self)

    def get_allocator(self):
        return _carray.vectord_get_allocator(self)

    def pop_back(self):
        return _carray.vectord_pop_back(self)

    def erase(self, *args):
        return _carray.vectord_erase(self, *args)

    def __init__(self, *args):
        this = _carray.new_vectord(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _carray.vectord_push_back(self, x)

    def front(self):
        return _carray.vectord_front(self)

    def back(self):
        return _carray.vectord_back(self)

    def assign(self, n, x):
        return _carray.vectord_assign(self, n, x)

    def resize(self, *args):
        return _carray.vectord_resize(self, *args)

    def insert(self, *args):
        return _carray.vectord_insert(self, *args)

    def reserve(self, n):
        return _carray.vectord_reserve(self, n)

    def capacity(self):
        return _carray.vectord_capacity(self)
    __swig_destroy__ = _carray.delete_vectord
    __del__ = lambda self: None
vectord_swigregister = _carray.vectord_swigregister
vectord_swigregister(vectord)

class vectordd(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectordd, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectordd, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _carray.vectordd_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _carray.vectordd___nonzero__(self)

    def __bool__(self):
        return _carray.vectordd___bool__(self)

    def __len__(self):
        return _carray.vectordd___len__(self)

    def __getslice__(self, i, j):
        return _carray.vectordd___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _carray.vectordd___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _carray.vectordd___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _carray.vectordd___delitem__(self, *args)

    def __getitem__(self, *args):
        return _carray.vectordd___getitem__(self, *args)

    def __setitem__(self, *args):
        return _carray.vectordd___setitem__(self, *args)

    def pop(self):
        return _carray.vectordd_pop(self)

    def append(self, x):
        return _carray.vectordd_append(self, x)

    def empty(self):
        return _carray.vectordd_empty(self)

    def size(self):
        return _carray.vectordd_size(self)

    def swap(self, v):
        return _carray.vectordd_swap(self, v)

    def begin(self):
        return _carray.vectordd_begin(self)

    def end(self):
        return _carray.vectordd_end(self)

    def rbegin(self):
        return _carray.vectordd_rbegin(self)

    def rend(self):
        return _carray.vectordd_rend(self)

    def clear(self):
        return _carray.vectordd_clear(self)

    def get_allocator(self):
        return _carray.vectordd_get_allocator(self)

    def pop_back(self):
        return _carray.vectordd_pop_back(self)

    def erase(self, *args):
        return _carray.vectordd_erase(self, *args)

    def __init__(self, *args):
        this = _carray.new_vectordd(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _carray.vectordd_push_back(self, x)

    def front(self):
        return _carray.vectordd_front(self)

    def back(self):
        return _carray.vectordd_back(self)

    def assign(self, n, x):
        return _carray.vectordd_assign(self, n, x)

    def resize(self, *args):
        return _carray.vectordd_resize(self, *args)

    def insert(self, *args):
        return _carray.vectordd_insert(self, *args)

    def reserve(self, n):
        return _carray.vectordd_reserve(self, n)

    def capacity(self):
        return _carray.vectordd_capacity(self)
    __swig_destroy__ = _carray.delete_vectordd
    __del__ = lambda self: None
vectordd_swigregister = _carray.vectordd_swigregister
vectordd_swigregister(vectordd)


def ones(sz):
    return _carray.ones(sz)
ones = _carray.ones

def sum(v):
    return _carray.sum(v)
sum = _carray.sum

def view(v):
    return _carray.view(v)
view = _carray.view

def matrix_mul(mat1, mat2):
    return _carray.matrix_mul(mat1, mat2)
matrix_mul = _carray.matrix_mul
# This file is compatible with both classic and new-style classes.


